version: '2'

services:
    lino:
        # If you want to development and use another image,
        # change the image to the Dockerfile that corresponds to the one you want to use.
        image: guila/lino:latest
        ports:
            - 5002:5002
        volumes:
            - .:/2018.2-Lino
        stdin_open: true
        tty: true
        environment:
            - TRAINING_EPOCHS=60
            - TELEGRAM_ACCESS_TOKEN=543678173:AAGXV6Y-gjLs0iAr_BmroNGtz60OC5nTiSk
            - VERIFY=Lino_test_FGA_bot
            # - PSID= ${PSID}
            # - FACEBOOK_ACCESS_TOKEN= ${FACEBOOK_ACCESS_TOKEN}
            # - SECRET= ${SECRET}
            - WEBHOOK_URL=https://7e5b2d05.ngrok.io/webhook
            - TELEGRAM_DB_URI=mongodb://mongo_lino:27010/lino_telegram
            # - FACEBOOK_DB_URI= ${FACEBOOK_DB_URI}
        # bot credentials in train.py or another train file.
        depends_on:
            - cronjob
            - mongo_telegram
            - mongo_facebook

    mongo_telegram:
        image: mongo:latest
        command: mongod --port 27010
        volumes:
            - /l/mongo_telegram/mongo_telegram_db:/data/db
        ports:
            - 27010:27010

    mongo_facebook:
        image: mongo:latest
        command: mongod --port 27011
        volumes:
            - /l/mongo_facebook/mongo_facebook_db:/data/db
        ports:
            - 27011:27011

    cronjob:
        image: guila/cronjob:latest
        volumes:
            - ./outputs:/home
        stdin_open: true
        tty: true
        environment:
            - URI_TELEGRAM=mongodb://mongo_lino:27010/lino_telegram
            # - URI_FACEBOOK: ${URI_FACEBOOK}
            - TELEGRAM_ACCESS_TOKEN=543678173:AAGXV6Y-gjLs0iAr_BmroNGtz60OC5nTiSk
            # - FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
            # - PSID: ${PSID}
        depends_on:
            - mongo_telegram
            - mongo_facebook
#     elasticsearch:
#         image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
#         container_name: elasticsearch_540
#         environment:
#             - http.host=0.0.0.0
#             - transport.host=0.0.0.0
#             - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#             - ELASTIC_PASSWORD=changeme
#         volumes:
#             - esdata:/usr/share/elasticsearch/data
#             - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#         ports:
#             - 9200:9200
#             - 9300:9300
#         ulimits:
#             memlock:
#                 soft: -1
#                 hard: -1
#             nofile:
#                 soft: 65536
#                 hard: 65536
#         mem_limit: 2g
#         cap_add:
#             - IPC_LOCK

#     kibana:
#         image: docker.elastic.co/kibana/kibana:6.2.4
#         container_name: kibana-products-624
#         hostname: kibana
#         restart: always
#         environment:
#             - SERVER_NAME=kibana.localhost
#             - ELASTICSEARCH_URL=http://localhost:9200
#             - ELASTICSEARCH_USERNAME=elastic
#             - ELASTICSEARCH_HOST=elasticsearch
#             - ELASTICSEARCH_PORT=9200
#             - ELASTIC_PWD=changeme
#             - KIBANA_PWD=changeme
#         ports:
#             - "5601:5601"
#         expose:
#             - "5601"
#         links:
#         - elasticsearch
#         depends_on:
#         - elasticsearch

# volumes:
#     esdata:
#         driver: local
