version: '3'

services:
    lino:
        # If you want to development and use another image,
        # change the image to the Dockerfile that corresponds to the one you want to use.
        build:
            context: .
            dockerfile: docker/Messenger.Dockerfile
        ports:
            - 5001:5001
        volumes:
            - .:/2018.2-Lino
        stdin_open: true
        tty: true

        # If you want to development, remove the environment and set your own
        # bot credentials in train.py or another train file.
        depends_on:
            - cronjob
            - mongo_telegram
            - mongo_facebook

    mongo_telegram:
        image: mongo:latest
        command: mongod --port 27010
        volumes:
            - /l/mongo_telegram/mongo_telegram_db:/data/db
        ports:
            - 27010:27010

    mongo_facebook:
        image: mongo:latest
        command: mongod --port 27011
        volumes:
            - /l/mongo_facebook/mongo_facebook_db:/data/db
        ports:
            - 27011:27011

    cronjob:
        image: guila/cronjob:latest
        volumes:
            - ./outputs:/home
        depends_on:
            - webcrawler

    webcrawler:
        image: guila/webcrawler:latest
        ports:
            - 5000:5000
        depends_on:
            - mongo_ru

    mongo_ru:
        image: mongo:latest
        volumes:
            - /l/crawler/crawler_db:/data/db
        ports:
            - 27017:27017
