version: '3'

services:
    lino:
        # If you want to development and use another image,
        # change the image to the Dockerfile that corresponds to the one you want to use.
        image: guila/lino:latest
        ports:
            - 5002:5002
        volumes:
            - .:/2018.2-Lino
        stdin_open: true
        tty: true
        environment:
            - TRAINING_EPOCHS: ${TRAINING_EPOCHS}
            - TELEGRAM_ACCESS_TOKEN: ${TELEGRAM_ACCESS_TOKEN}
            - VERIFY: ${VERIFY}
            - PSID: ${PSID}
            - FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
            - SECRET: ${SECRET}
            - WEBHOOK_URL: ${WEBHOOK_URL}
            - TELEGRAM_DB_URI: ${TELEGRAM_DB_URI}
            - FACEBOOK_DB_URI: ${FACEBOOK_DB_URI}
        # bot credentials in train.py or another train file.
        depends_on:
            - cronjob
            - mongo_telegram
            - mongo_facebook

    mongo_telegram:
        image: mongo:latest
        command: mongod --port 27010
        volumes:
            - /l/mongo_telegram/mongo_telegram_db:/data/db
        ports:
            - 27010:27010

    mongo_facebook:
        image: mongo:latest
        command: mongod --port 27011
        volumes:
            - /l/mongo_facebook/mongo_facebook_db:/data/db
        ports:
            - 27011:27011

    cronjob:
        image: guila/cronjob:latest
        volumes:
            - ./outputs:/home
        stdin_open: true
        tty: true
        environment:
            - URI_TELEGRAM: ${URI_TELEGRAM}
            - URI_FACEBOOK: ${URI_FACEBOOK}
            - TELEGRAM_ACCESS_TOKEN: ${TELEGRAM_ACCESS_TOKEN}
            - FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
            - PSID: ${PSID}
        depends_on:
            - webcrawler
            - mongo_telegram
            - mongo_facebook

    webcrawler:
        image: guila/webcrawler:latest
        ports:
            - 5000:5000
        depends_on:
            - mongo_ru

    mongo_ru:
        image: mongo:latest
        volumes:
            - /l/crawler/crawler_db:/data/db
        ports:
            - 27017:27017
