version: '3'

services:
    lino:
        build:
            context: .
            dockerfile: docker/Telegram.Dockerfile
        ports:
            - 5002:5002
        volumes:
            - .:/2018.2-Lino
        depends_on:
            - mongo_ru
    debian:
        build:
            context: .
            dockerfile: ./cronjob.Dockerfile
        volumes:
            - ./outputs:/home
        depends_on:
            - webcrawler
    webcrawler:
        build:
            context: ../Lino-WebCrawler
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ../Lino-WebCrawler:/Lino-WebCrawler
    mongo_ru:
        image: mongo:latest
        volumes:
            - /data/db
        ports:
            - 27017:27017
