version: '3'

services:
    lino:
        build:
            context: .
            dockerfile: docker/Telegram.Dockerfile
        ports:
            - 5002:5002
        volumes:
            - .:/2018.2-Lino
        stdin_open: true
        tty: true
