version: '2'

services:
    lino:
        build: .
        ports:
            - 5005:5005
        volumes:
            - .:/2018.2-Lino
    debian:
        build:
            context: .
            dockerfile: ./cronjob.Dockerfile
        volumes:
            - ./outputs:/home
        depends_on:
            - webcrawler
    webcrawler:
        build:
            context: ../Lino-WebCrawler
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ../Lino-WebCrawler:/Lino-WebCrawler
