version: '3'

services:
    lino:
        # If you want to development and use another image,
        # change the image to the Dockerfile that corresponds to the one you want to use.
        image: guila/lino:latest
        ports:
            - 5002:5002
        volumes:
            - .:/2018.2-Lino
        stdin_open: true
        tty: true
        environment:
            - TRAINING_EPOCHS=60
            - TELEGRAM_ACCESS_TOKEN=885604002:AAHhPtkBB56JPfaCuDWD5QsrN8KCsNcH8jM
            - VERIFY=LuizLinoBot
            # - PSID: ${PSID
            # - FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
            # - SECRET: ${SECRET}
            - WEBHOOK_URL=https://104.248.67.4/webhook
            - TELEGRAM_DB_URI=mongodb://mongo_lino:27010/lino_telegram
            # - FACEBOOK_DB_URI: ${FACEBOOK_DB_URI}
        # bot credentials in train.py or another train file.
        depends_on:
            - cronjob
            - mongo_telegram
            # - mongo_facebook

    mongo_telegram:
        image: mongo:latest
        command: mongod --port 27010
        volumes:
            - /l/mongo_telegram/mongo_telegram_db:/data/db
        ports:
            - 27010:27010

    # mongo_facebook:
    #     image: mongo:latest
    #     command: mongod --port 27011
    #     volumes:
    #         - /l/mongo_facebook/mongo_facebook_db:/data/db
    #     ports:
    #         - 27011:27011

    cronjob:
        image: guila/cronjob:latest
        volumes:
            - ./outputs:/home
        stdin_open: true
        tty: true
        environment:
            - URI_TELEGRAM=mongodb://mongo_lino:27010/lino_telegram
            # - URI_FACEBOOK: ${URI_FACEBOOK}
            - TELEGRAM_ACCESS_TOKEN=885604002:AAHhPtkBB56JPfaCuDWD5QsrN8KCsNcH8jM
            # - FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
            # - PSID: ${PSID}
        depends_on:
            - mongo_telegram
            # - mongo_facebook
